name: Publish to NPM
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build package
        run: yarn build
      - name: Configure npm
        run: |
          echo 'https://registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          cat .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish package to NPM
        run: npm publish
