name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
jobs:
  build:
    name: Build, lint, tests and size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Bundle size check
        run: yarn bundlesize
